DROP DATABASE IF EXISTS `db_jobhunt`;
CREATE DATABASE `db_jobhunt`;


CREATE TABLE `job` (
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title NVARCHAR(255)
);


CREATE TABLE `applicant` (
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    full_name NVARCHAR(50) NOT NULL ,
    email VARCHAR(50) NOT NULL

);

CREATE TABLE `applicant_job` (
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

)




